tasks:
  - name: run arogyam-server
    openMode: split-left
    command: |
      docker-compose up arogyam-server
  
  - name: run arogyam-web
    openMode: split-right
    command: |
      npm install
      echo "REACT_APP_API_URL=$(gp url 8080)" > .env
      npm run start

ports:
  - name: arogyam-web
    port: 3000
    onOpen: open-browser

  - name: arogyam-server
    port: 8080
    onOpen: ignore
    visibility: public
