tasks:
  - name: run arogyam-server
    command: |
      echo "DB_URI=${DB_URI}" > .env
      echo "PORT=${PORT}" >> .env
      docker-compose up arogyam-server
  
  - name: run arogyam-web
    command: |
      npm install
      echo "REACT_APP_BACKEND_URL=$(gp url 8080)" >> .env
      npm run start

ports:
  - name: arogyam-web
    port: 3000
    onOpen: open-browser

  - name: arogyam-server
    port: 8080
    onOpen: ignore
    visibility: public
