version: '3.8'

services:
  arogyam-server:
    image: ali2722f/arogyam-backend:latest
    container_name: arogyam-server
    ports:
      - "8080:8080"  
    environment:
      - PORT=${SERVER_PORT} 
      - DB_URI=${DB_URI}
  arogyam-web:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    container_name: arogyam-web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    volumes:
      - /app/node_modules
      - ".:/app"
    depends_on:
      - arogyam-server