version: '3.8'

services:
  arogyam-server:
    image: ali2722f/arogyam-backend:latest
    container_name: arogyam-server
    ports:
      - "8080:8080"  
    environment:
      - PORT=8080 
      - DB_URI=mongodb+srv://sawansloka:arogyam@arogyam.pzo06.mongodb.net/local-test-service
  arogyam-web:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    container_name: arogyam-web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    volumes:
      - ".:/app"
    depends_on:
      - arogyam-server