version: '3.8'

services:
  arogyam-server:
    image: ali2722f/arogyam-backend:latest
    container_name: arogyam-server
    ports:
      - "8080:8080"  
    environment:
      - PORT=${SERVER_PORT} 
      - DB_URI=${DB_URI}
      - ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
  arogyam-web:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    container_name: arogyam-web
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    volumes:
      - /app/node_modules
      - ".:/app"
    depends_on:
      - arogyam-server